name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path-and-tags:
          - '8.0|8.0,latest'
          - '8.0'
          - '7.4'
          - '7.4'
          - '7.3'
          - '7.3'
          - '7.2'
          - '7.2'
          - '7.1'
          - '7.1'
          - '5.6'
    steps:
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)
      - id: get-id
        uses: actions/github-script@v5
        with:
          script: |
            const parts = context.matrix['path-and-tags'].value.split('-')
            core.setOutput('path', parts[0])

      - run: echo "${{ steps.get-id.outputs.path }}"
      # -
      #   name: Checkout
      #   uses: actions/checkout@v2
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ steps.split.outputs._0 }}
      #     platforms: linux/amd64,linux/arm64
      #     tags: ${{ steps.split.outputs._1 }}
      #     push: true
